"""Write the qualified matrix report from measured outputs, preserving caveats."""
import json,statistics
from datetime import datetime
from pathlib import Path
from audit_trait_matrix import audit
NAMES={'siege':'Siege Doctrine','efficient':'Efficient Logistics','mobile':'Mobile Capital','war_economy':'War Economy','martial':'Martial Culture','salvagers':'Salvagers','void':'Void Supremacy','swift':'Swift Mobilization','endurance':'Fleet Endurance','dread':'Dread Reputation','fortification':'Fortification Experts','industrial':'Industrial Efficiency'}
EFFECTS={'siege':'Losing ground-assault attrition; human setup ignores Defended difficulty','efficient':'Reinforce and Muster grant four instead of three','mobile':'Moving capital/shipyard; defence contributes strength; host damage and integrity','war_economy':'Three extra Supply each Logistics Cycle','martial':'Five extra Manpower each Logistics Cycle','salvagers':'Battle and capture Supply rewards','void':'Expansion has no Supply cost, including while Supply is locked','swift':'New fleets begin at three strength','endurance':'One strength restored at Logistics, capped at each fleet maximum','dread':'Reduced successful-defender resource returns under the applicable AI/player rules','fortification':'Two additional defence restored by Defend','industrial':'Four-Supply construction stages instead of five'}

def main():
 s=audit('trait-qualification-20260916');assert s['complete'],'Do not publish partial coverage as complete'
 lines=['# Faction traits and bot qualification','',f'Updated {datetime.now().strftime("%d %B %Y").lstrip("0")}. All 12 traits are applied mechanically and independently rotated across the production bot strategies. Traits are assigned between campaigns, never rerolled mid-game; rule-driven loss of a trait still applies.','','## Coverage','','The completed matrix contains **432 games**, each executing **100 Cycles**: 12 traits x 6 strategies x 3 turn positions x 2 matched replicates. Each trait appears as the focal faction in 36 games. Every strategy/seat combination appears for every trait. Opponent profiles and starting conditions vary between replicates but remain fixed across paired focal comparisons.','','This is a qualification screen, not an exhaustive set of three-trait combinations or a statistically precise ranking. The synthetic matrix has three systems; separate ten-system scenarios test larger campaigns. Close balance claims need more seeds, more opponent mixtures and maps appropriate to the intended campaign.','','| Trait | Games | Implemented interaction |','|---|---:|---|']
 for trait,name in NAMES.items():lines.append(f"| {name} | {s['by_trait'][trait]['games']} | {EFFECTS[trait]} |")
 lines+=['','## What changed in the bots','','Persistent operation plans connect fleet movement, assembly, repair, resources and attacks. The bots check actual combat effects, so a nominal win against an invulnerable shield is not mistaken for useful damage. Funding responds to enemy resources and upkeep. Plans distinguish new progress from a defender repairing the same damage repeatedly. Home defence evaluates resources as well as fleet strength. Free Void Supremacy expansion is no longer suppressed by a paid-expansion Supply reserve.','','The six strategies still share controller code; they are not six independent expert players. A separate siege controller and the older tactical controller are included as opponents to help expose shared weaknesses. Optional sampled search remains experimental and is outside horizon-zero qualification.','','## Measured results','',f"The matrix replayed and verified **{s['verified_orders']:,} orders** through the public rules interface. Initial/final snapshots, per-Cycle states, bot memory, event/combat logs and compressed complete order traces are retained.",'','| Milestone | Reached by Cycle 100 | Still unresolved | Mean among observed milestones | Observed range |','|---|---:|---:|---:|---|']
 for key,label in [('one_major_coalition','One surviving Major coalition'),('all_holdings_and_mobile_capitals','All holdings and Mobile Capitals controlled')]:
  v=s['milestones'][key];lines.append(f"| {label} | {v['observed']} | {v['censored_at_100']} | {v['observed_mean']:.1f} | {v['minimum']}-{v['maximum']} |")
 lines+=['','These are milestone times on small synthetic maps, not the duration of a representative campaign. Unresolved games are censored; the observed mean omits them and is not an estimated overall mean. No universal victory condition has been invented. The user target remains an average around 50-100 Cycles with shorter outliers.','','## Reading trait outcomes','','| Trait | Sole surviving focal faction | Focal faction survives | Mean captures |','|---|---:|---:|---:|']
 for trait,name in NAMES.items():
  v=s['by_trait'][trait];lines.append(f"| {name} | {v['sole_survivors']}/36 | {v['survivals']}/36 | {v['mean_captures']:.2f} |")
 lines+=['','These counts describe these bots and fixtures. They are not human win probabilities, significance tests, or approved nerfs/buffs. Siege Doctrine has a Soulstorm difficulty benefit, and Dread Reputation has player/AI return distinctions; their AI-only results cannot establish their full value in player battles. Opponent mixtures, position, map size, resource rules and strategy quality can all affect them. Use the saved decisions to investigate suspected causes before changing a trait.','','## Reproduction and state preservation','','The simulation bundle contains the source, input pins, all matrix results and compressed traces. trait_qualification.py reproduces the matrix; audit_trait_matrix.py checks coverage; validate_release.py checks the release gate. The handover records current status and remaining work. Dessica remains suspended at Cycle 21; no campaign turn, event or balance-rule change was made.']
 Path('Trait_Qualification_Report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
 Path('trait-qualification-20260916/summary.json').write_text(json.dumps(s,indent=2),encoding='utf-8')
if __name__=='__main__':main()
